apiVersion: v1
kind: Secret
metadata:
  name: job-market-analyzer-api-secrets
  namespace: { { namespace } }
type: Opaque
stringData:
  { % for key, value in secrets.items() % }
  { { key } }: "{{ value }}"
  { % endfor % }