apiVersion: v1
kind: Service
metadata:
  name: job-market-analyzer-api-service
  namespace: { { namespace } }
spec:
  selector:
    app: job-market-analyzer-api
    branch: { { git_branch } }
  ports:
    - name: http4s-port
      port: 8080