apiVersion: v1
kind: Service
metadata:
  name: my-http4s-project-service
  namespace: { { namespace } }
spec:
  selector:
    app: my-http4s-project
    branch: { { git_branch } }
  ports:
    - name: http4s-port
      port: 8080