version: "3.9"

services:
#  nginx:
#    image: nginx:stable-alpine
#    healthcheck:
#      test: "curl -f http://localhost/service/info"
#      start_period: 5s
#      interval: 10s
#      timeout: 5s
#    depends_on:
#      api:
#        condition: service_healthy
#      front-end:
#        condition: service_healthy
#    ports:
#      - 443:443
#      - 80:80
#    volumes:
#      - "./nginx/ssl:/etc/ssl"
#      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
#
#  api:
#    image: ghcr.io/ruchira088/job-market-analyzer-api:dev
#    healthcheck:
#      test: "curl -f localhost:8080/service/info"
#      start_period: 5s
#      interval: 10s
#      timeout: 5s
#    depends_on:
#      migration-app:
#        condition: service_completed_successfully
#      redis:
#        condition: service_healthy
#      elasticsearch:
#        condition: service_healthy
#    environment:
#      ELASTICSEARCH_HOST: elasticsearch
#      ELASTICSEARCH_PORT: 9200
#      ELASTICSEARCH_USERNAME: "elastic"
#      ELASTICSEARCH_PASSWORD: "my-password"
#      ENCRYPTION_KEY: "ahV2wB8G+6hQDwzfFoZcKlM4KC//qjA0Jq3TjewqgGQ="
#      DEFAULT_IV: "W6qURTo/i3zikcdrBpC/LQ=="
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      REDIS_PASSWORD: "my-redis-password"
#
#  front-end:
#    image: ghcr.io/ruchira088/job-market-analyzer-front-end:main
#    healthcheck:
#      test: "curl -f http://localhost"
#      start_period: 5s
#      interval: 3s
#      timeout: 2s

  postgres:
    image: postgres:15
    healthcheck:
      test: "pg_isready -U admin -d job-market-analyzer"
      start_period: 10s
      interval: 10s
      timeout: 5s
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: job-market-analyzer
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

  redis:
    image: bitnami/redis:7.0
    healthcheck:
      test: "redis-cli ping"
      start_period: 2s
      interval: 4s
      timeout: 2s
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: "my-redis-password"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    healthcheck:
      test: "curl -f -u elastic:my-password http://localhost:9200/_cluster/health"
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - 9200:9200
    environment:
      ELASTIC_PASSWORD: "my-password"
      "discovery.type": single-node
      "xpack.security.http.ssl.enabled": false

  migration-app:
    image: ghcr.io/ruchira088/job-market-analyzer-migration-app:dev
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "my-password"
      DATABASE_URL: jdbc:postgresql://postgres:5432/job-market-analyzer
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"

  kibana-users:
    image: curlimages/curl
    depends_on:
      elasticsearch:
        condition: service_healthy
    command:
      - /opt/scripts/create_kibana_users.sh
    volumes:
      - ./kibana:/opt/scripts
    environment:
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "my-password"
      KIBANA_USER: "kibana-user"
      KIBANA_PASSWORD: "kibana-password"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana-users:
        condition: service_completed_successfully
    healthcheck:
      test: "curl -f http://localhost:5601/status"
      start_period: 5s
      interval: 10s
      timeout: 5s
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: "kibana-user"
      ELASTICSEARCH_PASSWORD: "kibana-password"