version: "3.9"

services:
  api:
    image: ghcr.io/ruchira088/job-market-analyzer-api:main
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ENCRYPTION_KEY: "ahV2wB8G+6hQDwzfFoZcKlM4KC//qjA0Jq3TjewqgGQ="
      DEFAULT_IV: "W6qURTo/i3zikcdrBpC/LQ=="
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "my-redis-password"

  redis:
    image: bitnami/redis:7.0
    healthcheck:
      test: "redis-cli ping"
      start_period: 2s
      interval: 4s
      timeout: 2s
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: "my-redis-password"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    healthcheck:
      test: "curl http://localhost:9200/_cluster/health"
      start_period: 5s
      interval: 10s
      timeout: 5s
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      "discovery.type": single-node
      "xpack.security.enabled": false

  kibana:
    image: kibana:8.4.3
    healthcheck:
      test: "curl http://localhost:5601/status"
      start_period: 5s
      interval: 10s
      timeout: 5s
    ports:
      - 5601:5601