- set_fact:
    config_values:
      production:
        redis_hostname: server.internal.ruchij.com
        redis_port: 6378
        elasticsearch_host: server.internal.ruchij.com
        elasticsearch_port: 9200
        elasticsearch_index_prefix: prod
        database_url: jdbc:postgresql://server.internal.ruchij.com:5440/job-market-analyzer
      development:
        redis_hostname: server.internal.ruchij.com
        redis_port: 6381
        elasticsearch_host: server.internal.ruchij.com
        elasticsearch_port: 9200
        elasticsearch_index_prefix: dev
        database_url: jdbc:postgresql://server.internal.ruchij.com:5430/job-market-analyzer
    secrets:
      database_user: "{{ lookup('aws_ssm', '/job-market-analyzer/' + env + '/database/user', region='ap-southeast-2') }}"
      database_password: "{{ lookup('aws_ssm', '/job-market-analyzer/' + env + '/database/password', region='ap-southeast-2') }}"
      elasticsearch_username: "{{ lookup('aws_ssm', '/job-market-analyzer/' + env + '/elasticsearch/username', region='ap-southeast-2') }}"
      elasticsearch_password: "{{ lookup('aws_ssm', '/job-market-analyzer/' + env + '/elasticsearch/password', region='ap-southeast-2') }}"
      redis_password: "{{ lookup('aws_ssm', '/job-market-analyzer/' + env + '/redis/password', region='ap-southeast-2') }}"
      encryption_key: "{{ lookup('aws_ssm', '/job-market-analyzer/' + env + '/encryption-key', region='ap-southeast-2') }}"
      default_iv: "{{ lookup('aws_ssm', '/job-market-analyzer/' + env + '/default-iv', region='ap-southeast-2') }}"

- set_fact:
    api:
      config_values:
        DATABASE_URL: "{{ config_values[env].database_url }}"
        HEADLESS_MODE: "true"
        WEB_BROWSER: FIREFOX
        REDIS_HOST: "{{ config_values[env].redis_hostname }}"
        REDIS_PORT: "{{ config_values[env].redis_port }}"
        ELASTICSEARCH_HOST: "{{ config_values[env].elasticsearch_host }}"
        ELASTICSEARCH_PORT: "{{ config_values[env].elasticsearch_port }}"
        ELASTICSEARCH_INDEX_PREFIX: "{{ config_values[env].elasticsearch_index_prefix }}"
      secrets:
        DATABASE_USER: "{{ secrets.database_user }}"
        DATABASE_PASSWORD: "{{ secrets.database_password }}"
        REDIS_PASSWORD: "{{ secrets.redis_password }}"
        ELASTICSEARCH_USERNAME: "{{ secrets.elasticsearch_username }}"
        ELASTICSEARCH_PASSWORD: "{{ secrets.elasticsearch_password }}"
        ENCRYPTION_KEY: "{{ secrets.encryption_key }}"
        DEFAULT_IV: "{{ secrets.default_iv }}"
    migration_app:
      config_values:
        ELASTICSEARCH_HOST: "{{ config_values[env].elasticsearch_host }}"
        ELASTICSEARCH_PORT: "{{ config_values[env].elasticsearch_port }}"
        ELASTICSEARCH_INDEX_PREFIX: "{{ config_values[env].elasticsearch_index_prefix }}"
        DATABASE_URL: "{{ config_values[env].database_url }}"
      secrets:
        ELASTICSEARCH_USERNAME: "{{ secrets.elasticsearch_username }}"
        ELASTICSEARCH_PASSWORD: "{{ secrets.elasticsearch_password }}"
        DATABASE_USER: "{{ secrets.database_user }}"
        DATABASE_PASSWORD: "{{ secrets.database_password }}"