- set_fact:
    config_values:
      redis_hostname: redis-master
      elasticsearch_host: job-market-analyzer-es-http
    secrets:
      elasticsearch_username: "{{ lookup('aws_ssm', '/job-market-analyzer/' + env + '/elasticsearch/username', region='ap-southeast-2')}}"
      elasticsearch_password: "{{ lookup('aws_ssm', '/job-market-analyzer/' + git_branch + '/elasticsearch/password', region='ap-southeast-2')}}"
      redis_password: "{{ lookup('aws_ssm', '/job-market-analyzer/' + env + '/redis/password', region='ap-southeast-2')}}"

- set_fact:
    api:
      config_values:
        REDIS_HOSTNAME: "{{ config_values.redis_hostname }}"
        ELASTICSEARCH_HOST: "{{ config_values.elasticsearch_host }}"
      secrets:
        REDIS_PASSWORD: "{{ secrets.redis_password }}"
        ELASTICSEARCH_USERNAME: "{{ secrets.elasticsearch_username }}"
        ELASTICSEARCH_PASSWORD: "{{ secrets.elasticsearch_password }}"