FROM openjdk:17-slim

LABEL org.opencontainers.image.source https://github.com/ruchira088/job-market-analyzer

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/job-market-analyzer-{{ app }}

ADD {{ app }}.tar .

CMD [ "/opt/job-market-analyzer-{{ app }}/{{ app }}/bin/{{ app }}" ]
