version: "3.9"

services:
  postgres:
    image: postgres:15
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: "pg_isready -U admin -d job-market-analyzer"
      start_period: 10s
      interval: 10s
      timeout: 5s
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: job-market-analyzer
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "my-password"

  redis:
    image: bitnami/redis:7.0
    healthcheck:
      test: "redis-cli ping"
      start_period: 2s
      interval: 4s
      timeout: 2s
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: "redis-password"