apiVersion: batch/v1
kind: Job
metadata:
  name: job-market-analyzer-migration-app-job-{{ git_commit }}
  namespace: { { namespace } }
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: docker-registry-credentials
      containers:
        - name: job-market-analyzer-migration-app-container
          image: ghcr.io/ruchira088/job-market-analyzer-migration-app:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: job-market-analyzer-migration-app-data-config-map
            - secretRef:
                name: job-market-analyzer-migration-app-secrets
          volumeMounts:
            - mountPath: /opt/data
              name: file-config-map
      volumes:
        - name: file-config-map
          configMap:
            name: job-market-analyzer-migration-app-file-config-map