apiVersion: v1
kind: Secret
metadata:
  name: job-market-analyzer-migration-app-secrets
  namespace: {{ namespace }}
type: Opaque
stringData:
  {% for key, value in migration_app.secrets.items() %}
  {{ key }}: "{{ value }}"
  {% endfor %}