apiVersion: v1
kind: ConfigMap
metadata:
  name: job-market-analyzer-api-data-config-map
  namespace: {{ namespace }}
data:
  {% for key, value in api.config_values.items() %}
    {{ key }}: "{{ value }}"
    {% endfor %}
